### ISSUE TITLE
Result gives me "... 7 more items"

### ISSUE THREAD

**Issue by JGMAGNO** [thenativeweb/get-routes#156]
![image](https://user-images.githubusercontent.com/5405698/89094981-18d43080-d3fc-11ea-97a9-21a9188e13f6.png)

Whenever I get all routes in my projects, it gives me a text "... 7 more items"

**Comment by goloroden** [comment]
This looks like a shortened output of `console.log`, not like a bug in `get-routes`.

Hence closed.
