### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by ir-fuel** [thenativeweb/get-routes#5]
I don't know if this still works. To do something similar I had to use the following code

```
    const getRouter = () => {
      return app._router
    }

    getRouter().stack.forEach(function (r) {
      if (r.handle.stack)
        r.handle.stack.forEach((item) => {
          if (item.route)
            console.log(item.route.methods,item.route.path)
        })
    })
```

Which is completely different from your code? I am running `    "express": "^4.16.2"`

**Comment by goloroden** [comment]
Basically, nothing else is done [here](https://github.com/thenativeweb/get-routes/blob/master/lib/getRoutes.js#L62-L76).

What exactly is it that you think that does not work any more?

**Comment by ir-fuel** [comment]
Ok nvm, I never use lodash, it seems to go recursively over all properties. Thought it was a simple for loop.

My bad.
