### ISSUE TITLE
Fails with "Invalid method acl" for routes using "all"

### ISSUE THREAD

**Issue by mopagemo** [thenativeweb/get-routes#68]
For routes that use the "all" method get-routes fails with "Invalid method acl". This applies to routes like this:

```app.all('/foo/bar', foo.bar);```

**Comment by goloroden** [comment]
Would you mind coming up with a PR for that?

**Comment by goloroden** [comment]
We won't fix this for now, but if you want to come up with a PR, we would be more than happy to merge it 😊 

Hence closed for now.
