### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gbenthomas** [thenativeweb/get-routes#8]
Would it be possible to cut a new release for this package? I would like to use the updated dependencies due to some security issues with the version of lodash that is being used in the currently published version.

Thanks!

**Comment by goloroden** [comment]
Hi @gbenthomas 😊 

Thanks for asking, and yes – of course it's possible!

However, I would take the chance not only to bump the dependencies versions, but also to migrate this package to TypeScript (as we are doing with our entire codebase for everything), so please give me a few days … but there will be a new version soon 👍

**Comment by goloroden** [comment]
PS: `get-routes@1.0.0` is on npm, with the following things changed:

- The codebase has been migrated to TypeScript.
- Support for Sails.js has been dropped (we don't use it, so we don't want to support it in the long run).
- All dependencies have been updated.
- There is now a CircleCI build to run tests automatically on each commit / push.
- The project has been integrated with Dependabot, so in the future we will get updates for dependencies way more often than in the past.

Hope you like it 😊

**Comment by gbenthomas** [comment]
@goloroden Awesome! Thank you very much for the super quick update.

**Comment by goloroden** [comment]
You’re welcome 😊
